version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_familyflix
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: familyflix_db
            MYSQL_USER: familyflix
            MYSQL_PASSWORD: familyflix_ps
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    mysql_data:

networks:
    laravel_network:
        driver: bridge
